In [5]:
#COM PYTHON
preco = [1.00, 2.00, 3.00]
qtd = [1000, 2000, 3000]
vendas = sum([p * a for p, a in zip(preco,qtd)])
print(vendas)

#COM NUMPY
import numpy as np;
preco = np.array(preco)
qtd = np.array(qtd)
vendas = np.sum(preco * amount)
print(vendas)

#TENSOR BÁSICO
import tensorflow as tf
print(tf.__version__)
v1 = tf.Variable(0.0)
p1 = tf.placeholder(tf.float32)
new_val = tf.add(v1, p1)
update = tf.assign(v1, new_val)

with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  for _ in range(5):
    sess.run(update, feed_dict={p1: 1.0})
  print(sess.run(v1))



#DIVERSAS FORMAS DE CRIAR MATRIZES
x1 = [[1.0, 2.0],[3.0, 4.0]] #CORE PYTHON
x2 = np.array([[1.0, 2.0],[3.0, 4.0]], dtype=np.float32) #NUMPY
x3 = tf.constant([[1.0, 2.0],[3.0, 4.0]]) #TENSORFLOW
print(type(x1))
print(type(x2))
print(type(x3))

#Convertendo matrizes para tensores
t1 = tf.convert_to_tensor(x1, dtype=tf.float32)
t2 = tf.convert_to_tensor(x2, dtype=tf.float32)
t3 = tf.convert_to_tensor(x3, dtype=tf.float32)
print(type(t1))
print(type(t2))
print(type(t3))

#Usando uma sessão interativa
sess = tf.InteractiveSession()
raw_data = [1., 2., 8., -1., 0., 5.5, 6., 13]
spike = tf.Variable(False)
spike.initializer.run()
for i in range(1, len(raw_data)):
  if raw_data[i] - raw_data[i-1] > 5:
    updater = tf.assign(spike, True)
    updater.eval()
  else:
    tf.assign(spike, False).eval()
  print("Spike", spike.eval())
  
#criando uma matriz 500 X 500 composta por valores 0.5   
t1 = tf.ones([500,500], tf.float32) * 0.5
print(t1.eval())


sess.close()

14000.0
14000.0
1.13.1
5.0
<class 'list'>
<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
Spike False
Spike True
Spike False
Spike False
Spike True
Spike False
Spike True
[[0.5 0.5 0.5 ... 0.5 0.5 0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]
 ...
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]]
